# Generated by Django 5.2.7 on 2025-10-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecompras', '0002_produtos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='photo',
        ),
    ]
