# Generated by Django 5.2.7 on 2025-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecompras', '0003_remove_produtos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
