# Generated by Django 5.2.7 on 2025-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecompras', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='s_cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='s_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
