# Generated by Django 5.2.7 on 2025-10-26 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecompras', '0006_cart_s_cep_cart_s_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_cep', models.CharField(blank=True, max_length=9, null=True)),
                ('payment', models.CharField(choices=[('Pix', 'PIX'), ('Cartão', 'CARTÃO')], default='Pix', max_length=8)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitecompras.order')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecompras.produtos')),
            ],
        ),
    ]
