# Generated by Django 5.2.7 on 2025-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecompras', '0009_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto do produto'),
        ),
    ]
